<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.saCr6.k' shared service.

return $this->privates['.service_locator.saCr6.k'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['taskcategoryRepository' => function (): \App\Repository\TaskCategoryRepository {
    return ($this->privates['App\\Repository\\TaskCategoryRepository'] ?? $this->load('getTaskCategoryRepositoryService.php'));
}]);
