<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._YeZNPD' shared service.

return $this->privates['.service_locator._YeZNPD'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['hadoopStatusRepository' => function (): \App\Repository\HadoopStatusRepository {
    return ($this->privates['App\\Repository\\HadoopStatusRepository'] ?? $this->load('getHadoopStatusRepositoryService.php'));
}, 'logger' => function () {
    return ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());
}, 'queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}]);
