<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pbTBJz7' shared service.

return $this->privates['.service_locator.pbTBJz7'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['simulationRepository' => function (): \App\Repository\SimulationRepository {
    return ($this->privates['App\\Repository\\SimulationRepository'] ?? $this->load('getSimulationRepositoryService.php'));
}]);
