<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xr52zFV' shared service.

return $this->privates['.service_locator.Xr52zFV'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}, 'timesheetRepository' => function (): \App\Repository\TimesheetRepository {
    return ($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->load('getTimesheetRepositoryService.php'));
}]);
