<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.R9YCdUY' shared service.

return $this->privates['.service_locator.R9YCdUY'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}, 'simulationRepository' => function (): \App\Repository\SimulationRepository {
    return ($this->privates['App\\Repository\\SimulationRepository'] ?? $this->load('getSimulationRepositoryService.php'));
}]);
