<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._6uWQGA' shared service.

return $this->privates['.service_locator._6uWQGA'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['timesheetRepository' => function (): \App\Repository\TimesheetRepository {
    return ($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->load('getTimesheetRepositoryService.php'));
}]);
