<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dobcXP3' shared service.

return $this->privates['.service_locator.dobcXP3'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['projectrateRepository' => function (): \App\Repository\ProjectRateRepository {
    return ($this->privates['App\\Repository\\ProjectRateRepository'] ?? $this->load('getProjectRateRepositoryService.php'));
}]);
