<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ri73nW3' shared service.

return $this->privates['.service_locator.ri73nW3'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['filewatcherRepository' => function (): \App\Repository\FileWatcherRepository {
    return ($this->privates['App\\Repository\\FileWatcherRepository'] ?? $this->load('getFileWatcherRepositoryService.php'));
}]);
