<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MCpfYMk' shared service.

return $this->privates['.service_locator.MCpfYMk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['authenticationUtils' => function () {
    return ($this->services['security.authentication_utils'] ?? $this->load('getSecurity_AuthenticationUtilsService.php'));
}, 'container' => function () {
    return $this;
}, 'formFactory' => function () {
    return ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'));
}, 'twig' => function () {
    return ($this->services['twig'] ?? $this->getTwigService());
}]);
