<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AAu6m1b' shared service.

return $this->privates['.service_locator.AAu6m1b'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['projectAssignmentRepository' => function (): \App\Repository\ProjectAssignmentRepository {
    return ($this->privates['App\\Repository\\ProjectAssignmentRepository'] ?? $this->load('getProjectAssignmentRepositoryService.php'));
}, 'taskRepository' => function (): \App\Repository\TaskRepository {
    return ($this->privates['App\\Repository\\TaskRepository'] ?? $this->load('getTaskRepositoryService.php'));
}]);
