<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zFdZuSN' shared service.

return $this->privates['.service_locator.zFdZuSN'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['appUserRepository' => function (): \App\Repository\AppUserRepository {
    return ($this->privates['App\\Repository\\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php'));
}, 'awsCognitoClient' => function (): \App\Bridge\AwsCognitoClient {
    return ($this->privates['App\\Bridge\\AwsCognitoClient'] ?? $this->load('getAwsCognitoClientService.php'));
}, 'queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}]);
