<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pZ3G49N' shared service.

return $this->privates['.service_locator.pZ3G49N'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['conversionRepository' => function (): \App\Repository\ConversionRepository {
    return ($this->privates['App\\Repository\\ConversionRepository'] ?? $this->load('getConversionRepositoryService.php'));
}, 'queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}]);
