<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['App\\Controller\\AccountController::create' => function () {
    return ($this->privates['.service_locator.gd3_ogo'] ?? $this->load('get_ServiceLocator_Gd3OgoService.php'));
}, 'App\\Controller\\AccountController::delete' => function () {
    return ($this->privates['.service_locator.gd3_ogo'] ?? $this->load('get_ServiceLocator_Gd3OgoService.php'));
}, 'App\\Controller\\AccountController::index' => function () {
    return ($this->privates['.service_locator.vC9OS3x'] ?? $this->load('get_ServiceLocator_VC9OS3xService.php'));
}, 'App\\Controller\\AccountController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\AccountController::refresh' => function () {
    return ($this->privates['.service_locator.vC9OS3x'] ?? $this->load('get_ServiceLocator_VC9OS3xService.php'));
}, 'App\\Controller\\AppConfigurationController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\BaseController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ConversionController::activate' => function () {
    return ($this->privates['.service_locator.pZ3G49N'] ?? $this->load('get_ServiceLocator_PZ3G49NService.php'));
}, 'App\\Controller\\ConversionController::conversion' => function () {
    return ($this->privates['.service_locator.6PfOHK8'] ?? $this->load('get_ServiceLocator_6PfOHK8Service.php'));
}, 'App\\Controller\\ConversionController::create' => function () {
    return ($this->privates['.service_locator.pZ3G49N'] ?? $this->load('get_ServiceLocator_PZ3G49NService.php'));
}, 'App\\Controller\\ConversionController::delete' => function () {
    return ($this->privates['.service_locator.pZ3G49N'] ?? $this->load('get_ServiceLocator_PZ3G49NService.php'));
}, 'App\\Controller\\ConversionController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ConversionController::refresh' => function () {
    return ($this->privates['.service_locator.6PfOHK8'] ?? $this->load('get_ServiceLocator_6PfOHK8Service.php'));
}, 'App\\Controller\\DefaultController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\DefaultController::resetdata' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\FileUploadController::copyORC' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController::copyParquet' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController::copyToSharedFolder' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController::delete' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\FileUploadController::processS3Upload' => function () {
    return ($this->privates['.service_locator.84oRSq2'] ?? $this->load('get_ServiceLocator_84oRSq2Service.php'));
}, 'App\\Controller\\FileUploadController::restore' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController::upload' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\FileUploadController::uploads' => function () {
    return ($this->privates['.service_locator.89z_4OU'] ?? $this->load('get_ServiceLocator_89z4OUService.php'));
}, 'App\\Controller\\FileWatcherController::create' => function () {
    return ($this->privates['.service_locator.GK6npg9'] ?? $this->load('get_ServiceLocator_GK6npg9Service.php'));
}, 'App\\Controller\\FileWatcherController::delete' => function () {
    return ($this->privates['.service_locator.GK6npg9'] ?? $this->load('get_ServiceLocator_GK6npg9Service.php'));
}, 'App\\Controller\\FileWatcherController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\FileWatcherController::refresh' => function () {
    return ($this->privates['.service_locator.ri73nW3'] ?? $this->load('get_ServiceLocator_Ri73nW3Service.php'));
}, 'App\\Controller\\FileWatcherController::run' => function () {
    return ($this->privates['.service_locator.JskFAf1'] ?? $this->load('get_ServiceLocator_JskFAf1Service.php'));
}, 'App\\Controller\\FileWatcherController::watcher' => function () {
    return ($this->privates['.service_locator.ri73nW3'] ?? $this->load('get_ServiceLocator_Ri73nW3Service.php'));
}, 'App\\Controller\\HadoopStatusController::createHadoop' => function () {
    return ($this->privates['.service_locator.w3hd3Bt'] ?? $this->load('get_ServiceLocator_W3hd3BtService.php'));
}, 'App\\Controller\\HadoopStatusController::index' => function () {
    return ($this->privates['.service_locator.LAGdPau'] ?? $this->load('get_ServiceLocator_LAGdPauService.php'));
}, 'App\\Controller\\HadoopStatusController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\HadoopStatusController::refresh' => function () {
    return ($this->privates['.service_locator.LAGdPau'] ?? $this->load('get_ServiceLocator_LAGdPauService.php'));
}, 'App\\Controller\\HadoopStatusController::startHadoop' => function () {
    return ($this->privates['.service_locator._YeZNPD'] ?? $this->load('get_ServiceLocator_YeZNPDService.php'));
}, 'App\\Controller\\HadoopStatusController::stopHadoop' => function () {
    return ($this->privates['.service_locator._YeZNPD'] ?? $this->load('get_ServiceLocator_YeZNPDService.php'));
}, 'App\\Controller\\MPPStatusController::creatempp' => function () {
    return ($this->privates['.service_locator.6Y4E3LA'] ?? $this->load('get_ServiceLocator_6Y4E3LAService.php'));
}, 'App\\Controller\\MPPStatusController::index' => function () {
    return ($this->privates['.service_locator.IYdRsdu'] ?? $this->load('get_ServiceLocator_IYdRsduService.php'));
}, 'App\\Controller\\MPPStatusController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\MPPStatusController::refresh' => function () {
    return ($this->privates['.service_locator.IYdRsdu'] ?? $this->load('get_ServiceLocator_IYdRsduService.php'));
}, 'App\\Controller\\MPPStatusController::startmpp' => function () {
    return ($this->privates['.service_locator.N_Kn.CN'] ?? $this->load('get_ServiceLocator_NKn_CNService.php'));
}, 'App\\Controller\\MPPStatusController::stopmpp' => function () {
    return ($this->privates['.service_locator.N_Kn.CN'] ?? $this->load('get_ServiceLocator_NKn_CNService.php'));
}, 'App\\Controller\\NexusController::analysis' => function () {
    return ($this->privates['.service_locator.l6BODW6'] ?? $this->load('get_ServiceLocator_L6BODW6Service.php'));
}, 'App\\Controller\\NexusController::dataprofile' => function () {
    return ($this->privates['.service_locator.l6BODW6'] ?? $this->load('get_ServiceLocator_L6BODW6Service.php'));
}, 'App\\Controller\\NexusController::initialize' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\NexusController::metadata' => function () {
    return ($this->privates['.service_locator.Mg3IsZj'] ?? $this->load('get_ServiceLocator_Mg3IsZjService.php'));
}, 'App\\Controller\\NexusController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\NexusController::runanalysis' => function () {
    return ($this->privates['.service_locator.wuQfapA'] ?? $this->load('get_ServiceLocator_WuQfapAService.php'));
}, 'App\\Controller\\NexusController::rundataprofile' => function () {
    return ($this->privates['.service_locator.wuQfapA'] ?? $this->load('get_ServiceLocator_WuQfapAService.php'));
}, 'App\\Controller\\NexusController::setup' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\NexusController::upload' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\NotificationController::markRead' => function () {
    return ($this->privates['.service_locator.r66G1pO'] ?? $this->load('get_ServiceLocator_R66G1pOService.php'));
}, 'App\\Controller\\NotificationController::notifications' => function () {
    return ($this->privates['.service_locator.r66G1pO'] ?? $this->load('get_ServiceLocator_R66G1pOService.php'));
}, 'App\\Controller\\NotificationController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\NotificationController::pushNotification' => function () {
    return ($this->privates['.service_locator.r66G1pO'] ?? $this->load('get_ServiceLocator_R66G1pOService.php'));
}, 'App\\Controller\\ProjectAssignmentController::create' => function () {
    return ($this->privates['.service_locator.zwru4VC'] ?? $this->load('get_ServiceLocator_Zwru4VCService.php'));
}, 'App\\Controller\\ProjectAssignmentController::delete' => function () {
    return ($this->privates['.service_locator.zwru4VC'] ?? $this->load('get_ServiceLocator_Zwru4VCService.php'));
}, 'App\\Controller\\ProjectAssignmentController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ProjectAssignmentController::projects' => function () {
    return ($this->privates['.service_locator.rwqCNMm'] ?? $this->load('get_ServiceLocator_RwqCNMmService.php'));
}, 'App\\Controller\\ProjectAssignmentController::refresh' => function () {
    return ($this->privates['.service_locator.s1Db8OC'] ?? $this->load('get_ServiceLocator_S1Db8OCService.php'));
}, 'App\\Controller\\ProjectController::create' => function () {
    return ($this->privates['.service_locator.fz.EosS'] ?? $this->load('get_ServiceLocator_Fz_EosSService.php'));
}, 'App\\Controller\\ProjectController::delete' => function () {
    return ($this->privates['.service_locator.fz.EosS'] ?? $this->load('get_ServiceLocator_Fz_EosSService.php'));
}, 'App\\Controller\\ProjectController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ProjectController::project' => function () {
    return ($this->privates['.service_locator.L25Z_H9'] ?? $this->load('get_ServiceLocator_L25ZH9Service.php'));
}, 'App\\Controller\\ProjectController::refresh' => function () {
    return ($this->privates['.service_locator.L25Z_H9'] ?? $this->load('get_ServiceLocator_L25ZH9Service.php'));
}, 'App\\Controller\\ProjectRateController::create' => function () {
    return ($this->privates['.service_locator.XbrQYuN'] ?? $this->load('get_ServiceLocator_XbrQYuNService.php'));
}, 'App\\Controller\\ProjectRateController::delete' => function () {
    return ($this->privates['.service_locator.XbrQYuN'] ?? $this->load('get_ServiceLocator_XbrQYuNService.php'));
}, 'App\\Controller\\ProjectRateController::new' => function () {
    return ($this->privates['.service_locator.OqRGJ15'] ?? $this->load('get_ServiceLocator_OqRGJ15Service.php'));
}, 'App\\Controller\\ProjectRateController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ProjectRateController::projectrate' => function () {
    return ($this->privates['.service_locator.dobcXP3'] ?? $this->load('get_ServiceLocator_DobcXP3Service.php'));
}, 'App\\Controller\\ProjectRateController::refresh' => function () {
    return ($this->privates['.service_locator.dobcXP3'] ?? $this->load('get_ServiceLocator_DobcXP3Service.php'));
}, 'App\\Controller\\ProjectRateController::view' => function () {
    return ($this->privates['.service_locator.dobcXP3'] ?? $this->load('get_ServiceLocator_DobcXP3Service.php'));
}, 'App\\Controller\\QueryController::createQuery' => function () {
    return ($this->privates['.service_locator.Yl3nNM2'] ?? $this->load('get_ServiceLocator_Yl3nNM2Service.php'));
}, 'App\\Controller\\QueryController::delete' => function () {
    return ($this->privates['.service_locator.Yl3nNM2'] ?? $this->load('get_ServiceLocator_Yl3nNM2Service.php'));
}, 'App\\Controller\\QueryController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\QueryController::queries' => function () {
    return ($this->privates['.service_locator.lQH_o_L'] ?? $this->load('get_ServiceLocator_LQHOLService.php'));
}, 'App\\Controller\\QueryController::refresh' => function () {
    return ($this->privates['.service_locator.lQH_o_L'] ?? $this->load('get_ServiceLocator_LQHOLService.php'));
}, 'App\\Controller\\QueryController::run' => function () {
    return ($this->privates['.service_locator.ldAMdQU'] ?? $this->load('get_ServiceLocator_LdAMdQUService.php'));
}, 'App\\Controller\\SimulationController::create' => function () {
    return ($this->privates['.service_locator.R9YCdUY'] ?? $this->load('get_ServiceLocator_R9YCdUYService.php'));
}, 'App\\Controller\\SimulationController::delete' => function () {
    return ($this->privates['.service_locator.R9YCdUY'] ?? $this->load('get_ServiceLocator_R9YCdUYService.php'));
}, 'App\\Controller\\SimulationController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\SimulationController::refresh' => function () {
    return ($this->privates['.service_locator.pbTBJz7'] ?? $this->load('get_ServiceLocator_PbTBJz7Service.php'));
}, 'App\\Controller\\SimulationController::run' => function () {
    return ($this->privates['.service_locator.8KsR2PR'] ?? $this->load('get_ServiceLocator_8KsR2PRService.php'));
}, 'App\\Controller\\SimulationController::simulator' => function () {
    return ($this->privates['.service_locator.pbTBJz7'] ?? $this->load('get_ServiceLocator_PbTBJz7Service.php'));
}, 'App\\Controller\\SqsController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\SqsController::viewSQS' => function () {
    return ($this->privates['.service_locator.Drz357h'] ?? $this->load('get_ServiceLocator_Drz357hService.php'));
}, 'App\\Controller\\TableController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TableController::refresh' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TableController::search' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TableController::tables' => function () {
    return ($this->privates['.service_locator.a5iTCPh'] ?? $this->load('get_ServiceLocator_A5iTCPhService.php'));
}, 'App\\Controller\\TaskCategoryController::create' => function () {
    return ($this->privates['.service_locator.1z.nMr2'] ?? $this->load('get_ServiceLocator_1z_NMr2Service.php'));
}, 'App\\Controller\\TaskCategoryController::delete' => function () {
    return ($this->privates['.service_locator.1z.nMr2'] ?? $this->load('get_ServiceLocator_1z_NMr2Service.php'));
}, 'App\\Controller\\TaskCategoryController::new' => function () {
    return ($this->privates['.service_locator.eKnBq_t'] ?? $this->load('get_ServiceLocator_EKnBqTService.php'));
}, 'App\\Controller\\TaskCategoryController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskCategoryController::refresh' => function () {
    return ($this->privates['.service_locator.saCr6.k'] ?? $this->load('get_ServiceLocator_SaCr6_KService.php'));
}, 'App\\Controller\\TaskCategoryController::taskcategory' => function () {
    return ($this->privates['.service_locator.saCr6.k'] ?? $this->load('get_ServiceLocator_SaCr6_KService.php'));
}, 'App\\Controller\\TaskCategoryController::view' => function () {
    return ($this->privates['.service_locator.saCr6.k'] ?? $this->load('get_ServiceLocator_SaCr6_KService.php'));
}, 'App\\Controller\\TaskController::create' => function () {
    return ($this->privates['.service_locator.GT6TtVA'] ?? $this->load('get_ServiceLocator_GT6TtVAService.php'));
}, 'App\\Controller\\TaskController::delete' => function () {
    return ($this->privates['.service_locator.GT6TtVA'] ?? $this->load('get_ServiceLocator_GT6TtVAService.php'));
}, 'App\\Controller\\TaskController::new' => function () {
    return ($this->privates['.service_locator.AAu6m1b'] ?? $this->load('get_ServiceLocator_AAu6m1bService.php'));
}, 'App\\Controller\\TaskController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskController::refresh' => function () {
    return ($this->privates['.service_locator.a3Zzgn6'] ?? $this->load('get_ServiceLocator_A3Zzgn6Service.php'));
}, 'App\\Controller\\TaskController::task' => function () {
    return ($this->privates['.service_locator.a3Zzgn6'] ?? $this->load('get_ServiceLocator_A3Zzgn6Service.php'));
}, 'App\\Controller\\TaskController::view' => function () {
    return ($this->privates['.service_locator.a3Zzgn6'] ?? $this->load('get_ServiceLocator_A3Zzgn6Service.php'));
}, 'App\\Controller\\TaskQueueController::create' => function () {
    return ($this->privates['.service_locator.j0fGf3o'] ?? $this->load('get_ServiceLocator_J0fGf3oService.php'));
}, 'App\\Controller\\TaskQueueController::delete' => function () {
    return ($this->privates['.service_locator.j0fGf3o'] ?? $this->load('get_ServiceLocator_J0fGf3oService.php'));
}, 'App\\Controller\\TaskQueueController::new' => function () {
    return ($this->privates['.service_locator.ic.uFpj'] ?? $this->load('get_ServiceLocator_Ic_UFpjService.php'));
}, 'App\\Controller\\TaskQueueController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskQueueController::refresh' => function () {
    return ($this->privates['.service_locator.iVGcq9E'] ?? $this->load('get_ServiceLocator_IVGcq9EService.php'));
}, 'App\\Controller\\TaskQueueController::taskqueue' => function () {
    return ($this->privates['.service_locator.ic.uFpj'] ?? $this->load('get_ServiceLocator_Ic_UFpjService.php'));
}, 'App\\Controller\\TaskQueueController::view' => function () {
    return ($this->privates['.service_locator.iVGcq9E'] ?? $this->load('get_ServiceLocator_IVGcq9EService.php'));
}, 'App\\Controller\\TaskTemplateController::create' => function () {
    return ($this->privates['.service_locator.zMAyeEI'] ?? $this->load('get_ServiceLocator_ZMAyeEIService.php'));
}, 'App\\Controller\\TaskTemplateController::delete' => function () {
    return ($this->privates['.service_locator.zMAyeEI'] ?? $this->load('get_ServiceLocator_ZMAyeEIService.php'));
}, 'App\\Controller\\TaskTemplateController::new' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TaskTemplateController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskTemplateController::refresh' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TaskTemplateController::tasktemplate' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TaskTemplateController::view' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TemplateController::activate' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController::createTemplate' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController::deactivate' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController::delete' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController::index' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TemplateController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TemplateController::refresh' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TemplateController::sync' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController::wizard' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TimesheetController::create' => function () {
    return ($this->privates['.service_locator.Xr52zFV'] ?? $this->load('get_ServiceLocator_Xr52zFVService.php'));
}, 'App\\Controller\\TimesheetController::delete' => function () {
    return ($this->privates['.service_locator.Xr52zFV'] ?? $this->load('get_ServiceLocator_Xr52zFVService.php'));
}, 'App\\Controller\\TimesheetController::new' => function () {
    return ($this->privates['.service_locator.lStLV.C'] ?? $this->load('get_ServiceLocator_LStLV_CService.php'));
}, 'App\\Controller\\TimesheetController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TimesheetController::refresh' => function () {
    return ($this->privates['.service_locator._6uWQGA'] ?? $this->load('get_ServiceLocator_6uWQGAService.php'));
}, 'App\\Controller\\TimesheetController::timesheet' => function () {
    return ($this->privates['.service_locator.lStLV.C'] ?? $this->load('get_ServiceLocator_LStLV_CService.php'));
}, 'App\\Controller\\TimesheetController::view' => function () {
    return ($this->privates['.service_locator.vLmJ2oo'] ?? $this->load('get_ServiceLocator_VLmJ2ooService.php'));
}, 'App\\Controller\\User\\AppUserController::blankuser' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\AppUserController::changePassword' => function () {
    return ($this->privates['.service_locator.zFdZuSN'] ?? $this->load('get_ServiceLocator_ZFdZuSNService.php'));
}, 'App\\Controller\\User\\AppUserController::create' => function () {
    return ($this->privates['.service_locator.AIxSp9h'] ?? $this->load('get_ServiceLocator_AIxSp9hService.php'));
}, 'App\\Controller\\User\\AppUserController::delete' => function () {
    return ($this->privates['.service_locator.AIxSp9h'] ?? $this->load('get_ServiceLocator_AIxSp9hService.php'));
}, 'App\\Controller\\User\\AppUserController::edit' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\AppUserController::forgotpassword' => function () {
    return ($this->privates['.service_locator.oqn.ZnP'] ?? $this->load('get_ServiceLocator_Oqn_ZnPService.php'));
}, 'App\\Controller\\User\\AppUserController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\User\\AppUserController::processForgotPassword' => function () {
    return ($this->privates['.service_locator.m7OzrfU'] ?? $this->load('get_ServiceLocator_M7OzrfUService.php'));
}, 'App\\Controller\\User\\AppUserController::processResetPassword' => function () {
    return ($this->privates['.service_locator.Ex.y.KO'] ?? $this->load('get_ServiceLocator_Ex_Y_KOService.php'));
}, 'App\\Controller\\User\\AppUserController::showResetPassword' => function () {
    return ($this->privates['.service_locator.WJfzm_w'] ?? $this->load('get_ServiceLocator_WJfzmWService.php'));
}, 'App\\Controller\\User\\AppUserController::users' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\ForgotPasswordController::__invoke' => function () {
    return ($this->privates['.service_locator.52AVVAv'] ?? $this->load('get_ServiceLocator_52AVVAvService.php'));
}, 'App\\Controller\\User\\LoginController::__invoke' => function () {
    return ($this->privates['.service_locator.MCpfYMk'] ?? $this->load('get_ServiceLocator_MCpfYMkService.php'));
}, 'App\\Controller\\User\\ProfileController::processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\User\\ProfileController::profile' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\ResetPasswordController::__invoke' => function () {
    return ($this->privates['.service_locator.4twBeMr'] ?? $this->load('get_ServiceLocator_4twBeMrService.php'));
}, 'App\\Controller\\AccountController:create' => function () {
    return ($this->privates['.service_locator.gd3_ogo'] ?? $this->load('get_ServiceLocator_Gd3OgoService.php'));
}, 'App\\Controller\\AccountController:delete' => function () {
    return ($this->privates['.service_locator.gd3_ogo'] ?? $this->load('get_ServiceLocator_Gd3OgoService.php'));
}, 'App\\Controller\\AccountController:index' => function () {
    return ($this->privates['.service_locator.vC9OS3x'] ?? $this->load('get_ServiceLocator_VC9OS3xService.php'));
}, 'App\\Controller\\AccountController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\AccountController:refresh' => function () {
    return ($this->privates['.service_locator.vC9OS3x'] ?? $this->load('get_ServiceLocator_VC9OS3xService.php'));
}, 'App\\Controller\\AppConfigurationController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\BaseController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ConversionController:activate' => function () {
    return ($this->privates['.service_locator.pZ3G49N'] ?? $this->load('get_ServiceLocator_PZ3G49NService.php'));
}, 'App\\Controller\\ConversionController:conversion' => function () {
    return ($this->privates['.service_locator.6PfOHK8'] ?? $this->load('get_ServiceLocator_6PfOHK8Service.php'));
}, 'App\\Controller\\ConversionController:create' => function () {
    return ($this->privates['.service_locator.pZ3G49N'] ?? $this->load('get_ServiceLocator_PZ3G49NService.php'));
}, 'App\\Controller\\ConversionController:delete' => function () {
    return ($this->privates['.service_locator.pZ3G49N'] ?? $this->load('get_ServiceLocator_PZ3G49NService.php'));
}, 'App\\Controller\\ConversionController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ConversionController:refresh' => function () {
    return ($this->privates['.service_locator.6PfOHK8'] ?? $this->load('get_ServiceLocator_6PfOHK8Service.php'));
}, 'App\\Controller\\DefaultController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\DefaultController:resetdata' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\FileUploadController:copyORC' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController:copyParquet' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController:copyToSharedFolder' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController:delete' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\FileUploadController:processS3Upload' => function () {
    return ($this->privates['.service_locator.84oRSq2'] ?? $this->load('get_ServiceLocator_84oRSq2Service.php'));
}, 'App\\Controller\\FileUploadController:restore' => function () {
    return ($this->privates['.service_locator.FFDan3b'] ?? $this->load('get_ServiceLocator_FFDan3bService.php'));
}, 'App\\Controller\\FileUploadController:upload' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\FileUploadController:uploads' => function () {
    return ($this->privates['.service_locator.89z_4OU'] ?? $this->load('get_ServiceLocator_89z4OUService.php'));
}, 'App\\Controller\\FileWatcherController:create' => function () {
    return ($this->privates['.service_locator.GK6npg9'] ?? $this->load('get_ServiceLocator_GK6npg9Service.php'));
}, 'App\\Controller\\FileWatcherController:delete' => function () {
    return ($this->privates['.service_locator.GK6npg9'] ?? $this->load('get_ServiceLocator_GK6npg9Service.php'));
}, 'App\\Controller\\FileWatcherController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\FileWatcherController:refresh' => function () {
    return ($this->privates['.service_locator.ri73nW3'] ?? $this->load('get_ServiceLocator_Ri73nW3Service.php'));
}, 'App\\Controller\\FileWatcherController:run' => function () {
    return ($this->privates['.service_locator.JskFAf1'] ?? $this->load('get_ServiceLocator_JskFAf1Service.php'));
}, 'App\\Controller\\FileWatcherController:watcher' => function () {
    return ($this->privates['.service_locator.ri73nW3'] ?? $this->load('get_ServiceLocator_Ri73nW3Service.php'));
}, 'App\\Controller\\HadoopStatusController:createHadoop' => function () {
    return ($this->privates['.service_locator.w3hd3Bt'] ?? $this->load('get_ServiceLocator_W3hd3BtService.php'));
}, 'App\\Controller\\HadoopStatusController:index' => function () {
    return ($this->privates['.service_locator.LAGdPau'] ?? $this->load('get_ServiceLocator_LAGdPauService.php'));
}, 'App\\Controller\\HadoopStatusController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\HadoopStatusController:refresh' => function () {
    return ($this->privates['.service_locator.LAGdPau'] ?? $this->load('get_ServiceLocator_LAGdPauService.php'));
}, 'App\\Controller\\HadoopStatusController:startHadoop' => function () {
    return ($this->privates['.service_locator._YeZNPD'] ?? $this->load('get_ServiceLocator_YeZNPDService.php'));
}, 'App\\Controller\\HadoopStatusController:stopHadoop' => function () {
    return ($this->privates['.service_locator._YeZNPD'] ?? $this->load('get_ServiceLocator_YeZNPDService.php'));
}, 'App\\Controller\\MPPStatusController:creatempp' => function () {
    return ($this->privates['.service_locator.6Y4E3LA'] ?? $this->load('get_ServiceLocator_6Y4E3LAService.php'));
}, 'App\\Controller\\MPPStatusController:index' => function () {
    return ($this->privates['.service_locator.IYdRsdu'] ?? $this->load('get_ServiceLocator_IYdRsduService.php'));
}, 'App\\Controller\\MPPStatusController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\MPPStatusController:refresh' => function () {
    return ($this->privates['.service_locator.IYdRsdu'] ?? $this->load('get_ServiceLocator_IYdRsduService.php'));
}, 'App\\Controller\\MPPStatusController:startmpp' => function () {
    return ($this->privates['.service_locator.N_Kn.CN'] ?? $this->load('get_ServiceLocator_NKn_CNService.php'));
}, 'App\\Controller\\MPPStatusController:stopmpp' => function () {
    return ($this->privates['.service_locator.N_Kn.CN'] ?? $this->load('get_ServiceLocator_NKn_CNService.php'));
}, 'App\\Controller\\NexusController:analysis' => function () {
    return ($this->privates['.service_locator.l6BODW6'] ?? $this->load('get_ServiceLocator_L6BODW6Service.php'));
}, 'App\\Controller\\NexusController:dataprofile' => function () {
    return ($this->privates['.service_locator.l6BODW6'] ?? $this->load('get_ServiceLocator_L6BODW6Service.php'));
}, 'App\\Controller\\NexusController:initialize' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\NexusController:metadata' => function () {
    return ($this->privates['.service_locator.Mg3IsZj'] ?? $this->load('get_ServiceLocator_Mg3IsZjService.php'));
}, 'App\\Controller\\NexusController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\NexusController:runanalysis' => function () {
    return ($this->privates['.service_locator.wuQfapA'] ?? $this->load('get_ServiceLocator_WuQfapAService.php'));
}, 'App\\Controller\\NexusController:rundataprofile' => function () {
    return ($this->privates['.service_locator.wuQfapA'] ?? $this->load('get_ServiceLocator_WuQfapAService.php'));
}, 'App\\Controller\\NexusController:setup' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\NexusController:upload' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\NotificationController:markRead' => function () {
    return ($this->privates['.service_locator.r66G1pO'] ?? $this->load('get_ServiceLocator_R66G1pOService.php'));
}, 'App\\Controller\\NotificationController:notifications' => function () {
    return ($this->privates['.service_locator.r66G1pO'] ?? $this->load('get_ServiceLocator_R66G1pOService.php'));
}, 'App\\Controller\\NotificationController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\NotificationController:pushNotification' => function () {
    return ($this->privates['.service_locator.r66G1pO'] ?? $this->load('get_ServiceLocator_R66G1pOService.php'));
}, 'App\\Controller\\ProjectAssignmentController:create' => function () {
    return ($this->privates['.service_locator.zwru4VC'] ?? $this->load('get_ServiceLocator_Zwru4VCService.php'));
}, 'App\\Controller\\ProjectAssignmentController:delete' => function () {
    return ($this->privates['.service_locator.zwru4VC'] ?? $this->load('get_ServiceLocator_Zwru4VCService.php'));
}, 'App\\Controller\\ProjectAssignmentController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ProjectAssignmentController:projects' => function () {
    return ($this->privates['.service_locator.rwqCNMm'] ?? $this->load('get_ServiceLocator_RwqCNMmService.php'));
}, 'App\\Controller\\ProjectAssignmentController:refresh' => function () {
    return ($this->privates['.service_locator.s1Db8OC'] ?? $this->load('get_ServiceLocator_S1Db8OCService.php'));
}, 'App\\Controller\\ProjectController:create' => function () {
    return ($this->privates['.service_locator.fz.EosS'] ?? $this->load('get_ServiceLocator_Fz_EosSService.php'));
}, 'App\\Controller\\ProjectController:delete' => function () {
    return ($this->privates['.service_locator.fz.EosS'] ?? $this->load('get_ServiceLocator_Fz_EosSService.php'));
}, 'App\\Controller\\ProjectController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ProjectController:project' => function () {
    return ($this->privates['.service_locator.L25Z_H9'] ?? $this->load('get_ServiceLocator_L25ZH9Service.php'));
}, 'App\\Controller\\ProjectController:refresh' => function () {
    return ($this->privates['.service_locator.L25Z_H9'] ?? $this->load('get_ServiceLocator_L25ZH9Service.php'));
}, 'App\\Controller\\ProjectRateController:create' => function () {
    return ($this->privates['.service_locator.XbrQYuN'] ?? $this->load('get_ServiceLocator_XbrQYuNService.php'));
}, 'App\\Controller\\ProjectRateController:delete' => function () {
    return ($this->privates['.service_locator.XbrQYuN'] ?? $this->load('get_ServiceLocator_XbrQYuNService.php'));
}, 'App\\Controller\\ProjectRateController:new' => function () {
    return ($this->privates['.service_locator.OqRGJ15'] ?? $this->load('get_ServiceLocator_OqRGJ15Service.php'));
}, 'App\\Controller\\ProjectRateController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\ProjectRateController:projectrate' => function () {
    return ($this->privates['.service_locator.dobcXP3'] ?? $this->load('get_ServiceLocator_DobcXP3Service.php'));
}, 'App\\Controller\\ProjectRateController:refresh' => function () {
    return ($this->privates['.service_locator.dobcXP3'] ?? $this->load('get_ServiceLocator_DobcXP3Service.php'));
}, 'App\\Controller\\ProjectRateController:view' => function () {
    return ($this->privates['.service_locator.dobcXP3'] ?? $this->load('get_ServiceLocator_DobcXP3Service.php'));
}, 'App\\Controller\\QueryController:createQuery' => function () {
    return ($this->privates['.service_locator.Yl3nNM2'] ?? $this->load('get_ServiceLocator_Yl3nNM2Service.php'));
}, 'App\\Controller\\QueryController:delete' => function () {
    return ($this->privates['.service_locator.Yl3nNM2'] ?? $this->load('get_ServiceLocator_Yl3nNM2Service.php'));
}, 'App\\Controller\\QueryController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\QueryController:queries' => function () {
    return ($this->privates['.service_locator.lQH_o_L'] ?? $this->load('get_ServiceLocator_LQHOLService.php'));
}, 'App\\Controller\\QueryController:refresh' => function () {
    return ($this->privates['.service_locator.lQH_o_L'] ?? $this->load('get_ServiceLocator_LQHOLService.php'));
}, 'App\\Controller\\QueryController:run' => function () {
    return ($this->privates['.service_locator.ldAMdQU'] ?? $this->load('get_ServiceLocator_LdAMdQUService.php'));
}, 'App\\Controller\\SimulationController:create' => function () {
    return ($this->privates['.service_locator.R9YCdUY'] ?? $this->load('get_ServiceLocator_R9YCdUYService.php'));
}, 'App\\Controller\\SimulationController:delete' => function () {
    return ($this->privates['.service_locator.R9YCdUY'] ?? $this->load('get_ServiceLocator_R9YCdUYService.php'));
}, 'App\\Controller\\SimulationController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\SimulationController:refresh' => function () {
    return ($this->privates['.service_locator.pbTBJz7'] ?? $this->load('get_ServiceLocator_PbTBJz7Service.php'));
}, 'App\\Controller\\SimulationController:run' => function () {
    return ($this->privates['.service_locator.8KsR2PR'] ?? $this->load('get_ServiceLocator_8KsR2PRService.php'));
}, 'App\\Controller\\SimulationController:simulator' => function () {
    return ($this->privates['.service_locator.pbTBJz7'] ?? $this->load('get_ServiceLocator_PbTBJz7Service.php'));
}, 'App\\Controller\\SqsController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\SqsController:viewSQS' => function () {
    return ($this->privates['.service_locator.Drz357h'] ?? $this->load('get_ServiceLocator_Drz357hService.php'));
}, 'App\\Controller\\TableController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TableController:refresh' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TableController:search' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TableController:tables' => function () {
    return ($this->privates['.service_locator.a5iTCPh'] ?? $this->load('get_ServiceLocator_A5iTCPhService.php'));
}, 'App\\Controller\\TaskCategoryController:create' => function () {
    return ($this->privates['.service_locator.1z.nMr2'] ?? $this->load('get_ServiceLocator_1z_NMr2Service.php'));
}, 'App\\Controller\\TaskCategoryController:delete' => function () {
    return ($this->privates['.service_locator.1z.nMr2'] ?? $this->load('get_ServiceLocator_1z_NMr2Service.php'));
}, 'App\\Controller\\TaskCategoryController:new' => function () {
    return ($this->privates['.service_locator.eKnBq_t'] ?? $this->load('get_ServiceLocator_EKnBqTService.php'));
}, 'App\\Controller\\TaskCategoryController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskCategoryController:refresh' => function () {
    return ($this->privates['.service_locator.saCr6.k'] ?? $this->load('get_ServiceLocator_SaCr6_KService.php'));
}, 'App\\Controller\\TaskCategoryController:taskcategory' => function () {
    return ($this->privates['.service_locator.saCr6.k'] ?? $this->load('get_ServiceLocator_SaCr6_KService.php'));
}, 'App\\Controller\\TaskCategoryController:view' => function () {
    return ($this->privates['.service_locator.saCr6.k'] ?? $this->load('get_ServiceLocator_SaCr6_KService.php'));
}, 'App\\Controller\\TaskController:create' => function () {
    return ($this->privates['.service_locator.GT6TtVA'] ?? $this->load('get_ServiceLocator_GT6TtVAService.php'));
}, 'App\\Controller\\TaskController:delete' => function () {
    return ($this->privates['.service_locator.GT6TtVA'] ?? $this->load('get_ServiceLocator_GT6TtVAService.php'));
}, 'App\\Controller\\TaskController:new' => function () {
    return ($this->privates['.service_locator.AAu6m1b'] ?? $this->load('get_ServiceLocator_AAu6m1bService.php'));
}, 'App\\Controller\\TaskController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskController:refresh' => function () {
    return ($this->privates['.service_locator.a3Zzgn6'] ?? $this->load('get_ServiceLocator_A3Zzgn6Service.php'));
}, 'App\\Controller\\TaskController:task' => function () {
    return ($this->privates['.service_locator.a3Zzgn6'] ?? $this->load('get_ServiceLocator_A3Zzgn6Service.php'));
}, 'App\\Controller\\TaskController:view' => function () {
    return ($this->privates['.service_locator.a3Zzgn6'] ?? $this->load('get_ServiceLocator_A3Zzgn6Service.php'));
}, 'App\\Controller\\TaskQueueController:create' => function () {
    return ($this->privates['.service_locator.j0fGf3o'] ?? $this->load('get_ServiceLocator_J0fGf3oService.php'));
}, 'App\\Controller\\TaskQueueController:delete' => function () {
    return ($this->privates['.service_locator.j0fGf3o'] ?? $this->load('get_ServiceLocator_J0fGf3oService.php'));
}, 'App\\Controller\\TaskQueueController:new' => function () {
    return ($this->privates['.service_locator.ic.uFpj'] ?? $this->load('get_ServiceLocator_Ic_UFpjService.php'));
}, 'App\\Controller\\TaskQueueController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskQueueController:refresh' => function () {
    return ($this->privates['.service_locator.iVGcq9E'] ?? $this->load('get_ServiceLocator_IVGcq9EService.php'));
}, 'App\\Controller\\TaskQueueController:taskqueue' => function () {
    return ($this->privates['.service_locator.ic.uFpj'] ?? $this->load('get_ServiceLocator_Ic_UFpjService.php'));
}, 'App\\Controller\\TaskQueueController:view' => function () {
    return ($this->privates['.service_locator.iVGcq9E'] ?? $this->load('get_ServiceLocator_IVGcq9EService.php'));
}, 'App\\Controller\\TaskTemplateController:create' => function () {
    return ($this->privates['.service_locator.zMAyeEI'] ?? $this->load('get_ServiceLocator_ZMAyeEIService.php'));
}, 'App\\Controller\\TaskTemplateController:delete' => function () {
    return ($this->privates['.service_locator.zMAyeEI'] ?? $this->load('get_ServiceLocator_ZMAyeEIService.php'));
}, 'App\\Controller\\TaskTemplateController:new' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TaskTemplateController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TaskTemplateController:refresh' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TaskTemplateController:tasktemplate' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TaskTemplateController:view' => function () {
    return ($this->privates['.service_locator.9r3udEI'] ?? $this->load('get_ServiceLocator_9r3udEIService.php'));
}, 'App\\Controller\\TemplateController:activate' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController:createTemplate' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController:deactivate' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController:delete' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController:index' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TemplateController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TemplateController:refresh' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TemplateController:sync' => function () {
    return ($this->privates['.service_locator.6f1a_D2'] ?? $this->load('get_ServiceLocator_6f1aD2Service.php'));
}, 'App\\Controller\\TemplateController:wizard' => function () {
    return ($this->privates['.service_locator.Bp1iBfv'] ?? $this->load('get_ServiceLocator_Bp1iBfvService.php'));
}, 'App\\Controller\\TimesheetController:create' => function () {
    return ($this->privates['.service_locator.Xr52zFV'] ?? $this->load('get_ServiceLocator_Xr52zFVService.php'));
}, 'App\\Controller\\TimesheetController:delete' => function () {
    return ($this->privates['.service_locator.Xr52zFV'] ?? $this->load('get_ServiceLocator_Xr52zFVService.php'));
}, 'App\\Controller\\TimesheetController:new' => function () {
    return ($this->privates['.service_locator.lStLV.C'] ?? $this->load('get_ServiceLocator_LStLV_CService.php'));
}, 'App\\Controller\\TimesheetController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\TimesheetController:refresh' => function () {
    return ($this->privates['.service_locator._6uWQGA'] ?? $this->load('get_ServiceLocator_6uWQGAService.php'));
}, 'App\\Controller\\TimesheetController:timesheet' => function () {
    return ($this->privates['.service_locator.lStLV.C'] ?? $this->load('get_ServiceLocator_LStLV_CService.php'));
}, 'App\\Controller\\TimesheetController:view' => function () {
    return ($this->privates['.service_locator.vLmJ2oo'] ?? $this->load('get_ServiceLocator_VLmJ2ooService.php'));
}, 'App\\Controller\\User\\AppUserController:blankuser' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\AppUserController:changePassword' => function () {
    return ($this->privates['.service_locator.zFdZuSN'] ?? $this->load('get_ServiceLocator_ZFdZuSNService.php'));
}, 'App\\Controller\\User\\AppUserController:create' => function () {
    return ($this->privates['.service_locator.AIxSp9h'] ?? $this->load('get_ServiceLocator_AIxSp9hService.php'));
}, 'App\\Controller\\User\\AppUserController:delete' => function () {
    return ($this->privates['.service_locator.AIxSp9h'] ?? $this->load('get_ServiceLocator_AIxSp9hService.php'));
}, 'App\\Controller\\User\\AppUserController:edit' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\AppUserController:forgotpassword' => function () {
    return ($this->privates['.service_locator.oqn.ZnP'] ?? $this->load('get_ServiceLocator_Oqn_ZnPService.php'));
}, 'App\\Controller\\User\\AppUserController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\User\\AppUserController:processForgotPassword' => function () {
    return ($this->privates['.service_locator.m7OzrfU'] ?? $this->load('get_ServiceLocator_M7OzrfUService.php'));
}, 'App\\Controller\\User\\AppUserController:processResetPassword' => function () {
    return ($this->privates['.service_locator.Ex.y.KO'] ?? $this->load('get_ServiceLocator_Ex_Y_KOService.php'));
}, 'App\\Controller\\User\\AppUserController:showResetPassword' => function () {
    return ($this->privates['.service_locator.WJfzm_w'] ?? $this->load('get_ServiceLocator_WJfzmWService.php'));
}, 'App\\Controller\\User\\AppUserController:users' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\ForgotPasswordController:__invoke' => function () {
    return ($this->privates['.service_locator.52AVVAv'] ?? $this->load('get_ServiceLocator_52AVVAvService.php'));
}, 'App\\Controller\\User\\ForgotPasswordController' => function () {
    return ($this->privates['.service_locator.52AVVAv'] ?? $this->load('get_ServiceLocator_52AVVAvService.php'));
}, 'App\\Controller\\User\\LoginController:__invoke' => function () {
    return ($this->privates['.service_locator.MCpfYMk'] ?? $this->load('get_ServiceLocator_MCpfYMkService.php'));
}, 'App\\Controller\\User\\LoginController' => function () {
    return ($this->privates['.service_locator.MCpfYMk'] ?? $this->load('get_ServiceLocator_MCpfYMkService.php'));
}, 'App\\Controller\\User\\ProfileController:processAthenaQuery' => function () {
    return ($this->privates['.service_locator.CThpHJr'] ?? $this->load('get_ServiceLocator_CThpHJrService.php'));
}, 'App\\Controller\\User\\ProfileController:profile' => function () {
    return ($this->privates['.service_locator.8996nmF'] ?? $this->load('get_ServiceLocator_8996nmFService.php'));
}, 'App\\Controller\\User\\ResetPasswordController:__invoke' => function () {
    return ($this->privates['.service_locator.4twBeMr'] ?? $this->load('get_ServiceLocator_4twBeMrService.php'));
}, 'App\\Controller\\User\\ResetPasswordController' => function () {
    return ($this->privates['.service_locator.4twBeMr'] ?? $this->load('get_ServiceLocator_4twBeMrService.php'));
}]));
