<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MsgPhp\User\Infra\Console\Command\AddUserRoleCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Message/MessageReceivingInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Message/MessageDispatchingTrait.php';
include_once $this->targetDirs[3].'/vendor/msgphp/user/Infra/Console/Command/UserCommand.php';
include_once $this->targetDirs[3].'/vendor/msgphp/user/Infra/Console/Command/UserRoleCommand.php';
include_once $this->targetDirs[3].'/vendor/msgphp/user/Infra/Console/Command/AddUserRoleCommand.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/Context/ContextFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/Context/DoctrineEntityContextFactory.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/Context/ClassContextFactory.php';

$this->privates['MsgPhp\\User\\Infra\\Console\\Command\\AddUserRoleCommand'] = $instance = new \MsgPhp\User\Infra\Console\Command\AddUserRoleCommand(($this->privates['MsgPhp\\Domain\\Infra\\Doctrine\\EntityAwareFactory'] ?? $this->getEntityAwareFactoryService()), ($this->privates['MsgPhp\\Domain\\Message\\DomainMessageBus'] ?? $this->load('getDomainMessageBusService.php')), ($this->privates['MsgPhp\\User\\Infra\\Doctrine\\Repository\\UserRepository'] ?? $this->getUserRepositoryService()), ($this->privates['MsgPhp\\User\\Infra\\Doctrine\\Repository\\RoleRepository'] ?? $this->load('getRoleRepositoryService.php')), new \MsgPhp\Domain\Infra\Console\Context\DoctrineEntityContextFactory(new \MsgPhp\Domain\Infra\Console\Context\ClassContextFactory('App\\Entity\\User\\UserRole', '__construct', $this->parameters['msgphp.domain.class_mapping'], 4, ($this->privates['app.console.class_context_element_factory'] ?? $this->load('getApp_Console_ClassContextElementFactoryService.php'))), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'App\\Entity\\User\\UserRole'));

$instance->setName('user:role:add');

return $instance;
