<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.messenger_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Command/DebugCommand.php';

$this->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['messenger.bus.default' => ['MsgPhp\\User\\Command\\AddUserRoleCommand' => [0 => 'MsgPhp\\User\\Command\\Handler\\AddUserRoleHandler'], 'MsgPhp\\User\\Command\\ChangeUserCredentialCommand' => [0 => 'MsgPhp\\User\\Command\\Handler\\ChangeUserCredentialHandler'], 'MsgPhp\\User\\Command\\CreateUserCommand' => [0 => 'MsgPhp\\User\\Command\\Handler\\CreateUserHandler'], 'MsgPhp\\User\\Command\\DeleteUserCommand' => [0 => 'MsgPhp\\User\\Command\\Handler\\DeleteUserHandler'], 'MsgPhp\\User\\Command\\DeleteUserRoleCommand' => [0 => 'MsgPhp\\User\\Command\\Handler\\DeleteUserRoleHandler'], 'MsgPhp\\User\\Command\\RequestUserPasswordCommand' => [0 => 'MsgPhp\\User\\Command\\Handler\\RequestUserPasswordHandler']]]);

$instance->setName('debug:messenger');

return $instance;
