<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MsgPhp\User\Infra\Console\Command\CreateUserCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Message/MessageReceivingInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Message/MessageDispatchingTrait.php';
include_once $this->targetDirs[3].'/vendor/msgphp/user/Infra/Console/Command/CreateUserCommand.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/Context/ContextFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/Context/DoctrineEntityContextFactory.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/Context/ClassContextFactory.php';

$this->privates['MsgPhp\\User\\Infra\\Console\\Command\\CreateUserCommand'] = $instance = new \MsgPhp\User\Infra\Console\Command\CreateUserCommand(($this->privates['MsgPhp\\Domain\\Factory\\ClassMappingObjectFactory'] ?? $this->getClassMappingObjectFactoryService()), ($this->privates['MsgPhp\\Domain\\Message\\DomainMessageBus'] ?? $this->load('getDomainMessageBusService.php')), new \MsgPhp\Domain\Infra\Console\Context\DoctrineEntityContextFactory(new \MsgPhp\Domain\Infra\Console\Context\ClassContextFactory('App\\Entity\\User\\AppUser', '__construct', $this->parameters['msgphp.domain.class_mapping'], 0, ($this->privates['app.console.class_context_element_factory'] ?? $this->load('getApp_Console_ClassContextElementFactoryService.php'))), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'App\\Entity\\User\\AppUser'));

$instance->setName('user:create');

return $instance;
