<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MsgPhp\Domain\Message\DomainMessageBus' shared service.

include_once $this->targetDirs[3].'/vendor/msgphp/domain/Message/DomainMessageBusInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Message/DomainMessageBus.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Messenger/DomainMessageBus.php';

$a = ($this->services['message_bus'] ?? $this->load('getMessageBusService.php'));

return $this->privates['MsgPhp\\Domain\\Message\\DomainMessageBus'] = new \MsgPhp\Domain\Message\DomainMessageBus(new \MsgPhp\Domain\Infra\Messenger\DomainMessageBus($a), new \MsgPhp\Domain\Infra\Messenger\DomainMessageBus($a), $this->parameters['msgphp.domain.events']);
