<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.helper.raw_console_reporter' shared service.

include_once $this->targetDirs[3].'/vendor/zendframework/zenddiagnostics/src/Runner/Reporter/ReporterInterface.php';
include_once $this->targetDirs[3].'/vendor/liip/monitor-bundle/Helper/RawConsoleReporter.php';

return $this->services['liip_monitor.helper.raw_console_reporter'] = new \Liip\MonitorBundle\Helper\RawConsoleReporter();
