<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.helper.runner_manager' shared service.

include_once $this->targetDirs[3].'/vendor/liip/monitor-bundle/Helper/RunnerManager.php';

return $this->services['liip_monitor.helper.runner_manager'] = new \Liip\MonitorBundle\Helper\RunnerManager($this);
