<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.helper' shared service.

include_once $this->targetDirs[3].'/vendor/liip/monitor-bundle/Helper/PathHelper.php';

return $this->services['liip_monitor.helper'] = new \Liip\MonitorBundle\Helper\PathHelper(($this->privates['assets.packages'] ?? $this->getAssets_PackagesService()), ($this->services['router'] ?? $this->getRouterService()));
