<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'message_bus' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/MessageBusInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/TraceableMessageBus.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/MessageBus.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/LoggingMiddleware.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/EnvelopeAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Asynchronous/Middleware/SendMessageMiddleware.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Asynchronous/Routing/SenderLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Asynchronous/Routing/SenderLocator.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/Locator/HandlerLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/Locator/ContainerHandlerLocator.php';

$a = new \Symfony\Bridge\Monolog\Logger('messenger');
$a->pushHandler(($this->privates['cloudwatch_handler'] ?? $this->getCloudwatchHandlerService()));
$a->pushHandler(($this->privates['monolog.handler.console'] ?? ($this->privates['monolog.handler.console'] = new \Symfony\Bridge\Monolog\Handler\ConsoleHandler(NULL, true, []))));
$a->pushHandler(($this->privates['monolog.handler.container_logs'] ?? $this->getMonolog_Handler_ContainerLogsService()));
$a->pushHandler(($this->privates['monolog.handler.main'] ?? $this->getMonolog_Handler_MainService()));

return $this->services['message_bus'] = new \Symfony\Component\Messenger\TraceableMessageBus(new \Symfony\Component\Messenger\MessageBus([0 => new \Symfony\Component\Messenger\Middleware\LoggingMiddleware($a), 1 => new \Symfony\Component\Messenger\Asynchronous\Middleware\SendMessageMiddleware(new \Symfony\Component\Messenger\Asynchronous\Routing\SenderLocator(new \Symfony\Component\DependencyInjection\ServiceLocator([]), []), []), 2 => new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\Locator\ContainerHandlerLocator(new \Symfony\Component\DependencyInjection\ServiceLocator(['handler.MsgPhp\\User\\Command\\AddUserRoleCommand' => function () {
    return ($this->privates['MsgPhp\\User\\Command\\Handler\\AddUserRoleHandler'] ?? $this->load('getAddUserRoleHandlerService.php'));
}, 'handler.MsgPhp\\User\\Command\\ChangeUserCredentialCommand' => function () {
    return ($this->privates['MsgPhp\\User\\Command\\Handler\\ChangeUserCredentialHandler'] ?? $this->load('getChangeUserCredentialHandlerService.php'));
}, 'handler.MsgPhp\\User\\Command\\CreateUserCommand' => function () {
    return ($this->privates['MsgPhp\\User\\Command\\Handler\\CreateUserHandler'] ?? $this->load('getCreateUserHandlerService.php'));
}, 'handler.MsgPhp\\User\\Command\\DeleteUserCommand' => function () {
    return ($this->privates['MsgPhp\\User\\Command\\Handler\\DeleteUserHandler'] ?? $this->load('getDeleteUserHandlerService.php'));
}, 'handler.MsgPhp\\User\\Command\\DeleteUserRoleCommand' => function () {
    return ($this->privates['MsgPhp\\User\\Command\\Handler\\DeleteUserRoleHandler'] ?? $this->load('getDeleteUserRoleHandlerService.php'));
}, 'handler.MsgPhp\\User\\Command\\RequestUserPasswordCommand' => function () {
    return ($this->privates['MsgPhp\\User\\Command\\Handler\\RequestUserPasswordHandler'] ?? $this->load('getRequestUserPasswordHandlerService.php'));
}])))]));
