framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: { enabled: true }
    http_method_override: true
    translator: ~
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: '%session.lifetime.seconds%'
        gc_maxlifetime: '%session.lifetime.seconds%'

    #esi: true
    #fragments: true
    php_errors:
        log: true
