<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEd1MOu0\srcProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEd1MOu0/srcProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEd1MOu0.legacy');

    return;
}

if (!\class_exists(srcProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEd1MOu0\srcProdDebugProjectContainer::class, srcProdDebugProjectContainer::class, false);
}

return new \ContainerEd1MOu0\srcProdDebugProjectContainer([
    'container.build_hash' => 'Ed1MOu0',
    'container.build_id' => 'b628727f',
    'container.build_time' => 1580295225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEd1MOu0');
