<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XbrQYuN' shared service.

return $this->privates['.service_locator.XbrQYuN'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['projectrateRepository' => function (): \App\Repository\ProjectRateRepository {
    return ($this->privates['App\\Repository\\ProjectRateRepository'] ?? $this->load('getProjectRateRepositoryService.php'));
}, 'queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}]);
