<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lStLV.C' shared service.

return $this->privates['.service_locator.lStLV.C'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['projectAssignmentRepository' => function (): \App\Repository\ProjectAssignmentRepository {
    return ($this->privates['App\\Repository\\ProjectAssignmentRepository'] ?? $this->load('getProjectAssignmentRepositoryService.php'));
}, 'timesheetRepository' => function (): \App\Repository\TimesheetRepository {
    return ($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->load('getTimesheetRepositoryService.php'));
}]);
