<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.84oRSq2' shared service.

return $this->privates['.service_locator.84oRSq2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['cache' => function () {
    return ($this->services['cache.app'] ?? $this->load('getCache_AppService.php'));
}, 'fileUploadRepository' => function (): \App\Repository\FileUploadRepository {
    return ($this->privates['App\\Repository\\FileUploadRepository'] ?? $this->load('getFileUploadRepositoryService.php'));
}, 'sqsClient' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}, 'templateRepository' => function (): \App\Repository\TemplateRepository {
    return ($this->privates['App\\Repository\\TemplateRepository'] ?? $this->load('getTemplateRepositoryService.php'));
}, 'userRepository' => function (): \App\Repository\AppUserRepository {
    return ($this->privates['App\\Repository\\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php'));
}]);
