<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l6BODW6' shared service.

return $this->privates['.service_locator.l6BODW6'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['cache' => function () {
    return ($this->services['cache.app'] ?? $this->load('getCache_AppService.php'));
}, 'templateRepository' => function (): \App\Repository\TemplateRepository {
    return ($this->privates['App\\Repository\\TemplateRepository'] ?? $this->load('getTemplateRepositoryService.php'));
}]);
