<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oqn.ZnP' shared service.

return $this->privates['.service_locator.oqn.ZnP'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['formFactory' => function () {
    return ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'));
}]);
