<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8996nmF' shared service.

return $this->privates['.service_locator.8996nmF'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['appUserRepository' => function (): \App\Repository\AppUserRepository {
    return ($this->privates['App\\Repository\\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php'));
}, 'roleRepository' => function (): \MsgPhp\User\Infra\Doctrine\Repository\RoleRepository {
    return ($this->privates['MsgPhp\\User\\Infra\\Doctrine\\Repository\\RoleRepository'] ?? $this->load('getRoleRepositoryService.php'));
}]);
