<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vLmJ2oo' shared service.

return $this->privates['.service_locator.vLmJ2oo'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['timesheetDetailRepository' => function (): \App\Repository\TimesheetDetailRepository {
    return ($this->privates['App\\Repository\\TimesheetDetailRepository'] ?? $this->load('getTimesheetDetailRepositoryService.php'));
}, 'timesheetRepository' => function (): \App\Repository\TimesheetRepository {
    return ($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->load('getTimesheetRepositoryService.php'));
}]);
