<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ic.uFpj' shared service.

return $this->privates['.service_locator.ic.uFpj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['taskAssignmentRepository' => function (): \App\Repository\ProjectAssignmentRepository {
    return ($this->privates['App\\Repository\\ProjectAssignmentRepository'] ?? $this->load('getProjectAssignmentRepositoryService.php'));
}, 'taskqueueRepository' => function (): \App\Repository\TaskQueueRepository {
    return ($this->privates['App\\Repository\\TaskQueueRepository'] ?? $this->load('getTaskQueueRepositoryService.php'));
}]);
