<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.r66G1pO' shared service.

return $this->privates['.service_locator.r66G1pO'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['notificationRepository' => function (): \App\Repository\NotificationRepository {
    return ($this->privates['App\\Repository\\NotificationRepository'] ?? $this->load('getNotificationRepositoryService.php'));
}]);
