<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6f1a_D2' shared service.

return $this->privates['.service_locator.6f1a_D2'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}, 'templateRepository' => function (): \App\Repository\TemplateRepository {
    return ($this->privates['App\\Repository\\TemplateRepository'] ?? $this->load('getTemplateRepositoryService.php'));
}]);
