<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gd3_ogo' shared service.

return $this->privates['.service_locator.gd3_ogo'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['accountRepository' => function (): \App\Repository\AccountRepository {
    return ($this->privates['App\\Repository\\AccountRepository'] ?? $this->load('getAccountRepositoryService.php'));
}, 'queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}]);
