<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.s1Db8OC' shared service.

return $this->privates['.service_locator.s1Db8OC'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['appUserRepository' => function (): \App\Repository\AppUserRepository {
    return ($this->privates['App\\Repository\\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php'));
}, 'projectAssignmentRepository' => function (): \App\Repository\ProjectAssignmentRepository {
    return ($this->privates['App\\Repository\\ProjectAssignmentRepository'] ?? $this->load('getProjectAssignmentRepositoryService.php'));
}, 'projectRepository' => function (): \App\Repository\ProjectRepository {
    return ($this->privates['App\\Repository\\ProjectRepository'] ?? $this->load('getProjectRepositoryService.php'));
}]);
