<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9r3udEI' shared service.

return $this->privates['.service_locator.9r3udEI'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['tasktemplateRepository' => function (): \App\Repository\TaskTemplateRepository {
    return ($this->privates['App\\Repository\\TaskTemplateRepository'] ?? $this->load('getTaskTemplateRepositoryService.php'));
}]);
