<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CThpHJr' shared service.

return $this->privates['.service_locator.CThpHJr'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['athena' => function () {
    return ($this->privates['aws.athena'] ?? $this->load('getAws_AthenaService.php'));
}]);
