<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.m7OzrfU' shared service.

return $this->privates['.service_locator.m7OzrfU'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['appUserRepository' => function (): \App\Repository\AppUserRepository {
    return ($this->privates['App\\Repository\\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php'));
}, 'flashBag' => function () {
    return ($this->privates['session.flash_bag'] ?? ($this->privates['session.flash_bag'] = new \Symfony\Component\HttpFoundation\Session\Flash\FlashBag()));
}, 'formFactory' => function () {
    return ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'));
}, 'queue' => function () {
    return ($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php'));
}]);
