<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'aws.sqs' shared service.

include_once $this->targetDirs[3].'/vendor/aws/aws-sdk-php/src/Sqs/SqsClient.php';

return $this->privates['aws.sqs'] = ($this->privates['aws_sdk'] ?? $this->load('getAwsSdkService.php'))->createSqs();
