<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Bridge\AwsCognitoClient' shared autowired service.

include_once $this->targetDirs[3].'/src/Bridge/AwsCognitoClient.php';

return $this->privates['App\\Bridge\\AwsCognitoClient'] = new \App\Bridge\AwsCognitoClient('us-east-1_f2elqUMPV', '1ncuuvnku3u4hku6p11dnqiqgv', 'us-east-1', 'latest', 'AKIAIZ6ENRM52CQMFSTA', 'q4ShyCPF38sccLYwnb0hcmKtMl820Rx/jo5naFCA');
