<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'aws_sdk' shared service.

include_once $this->targetDirs[3].'/vendor/aws/aws-sdk-php/src/Sdk.php';

return $this->privates['aws_sdk'] = new \Aws\Sdk(['version' => 'latest', 'region' => 'us-east-1', 'credentials' => ['key' => 'AKIAIZ6ENRM52CQMFSTA', 'secret' => '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'], 'S3' => ['version' => 'latest', 'bucket' => 'yuva-bucket', 'region' => 'us-east-1'], 'Sqs' => ['queue_url' => 'https://sqs.us-east-1.amazonaws.com/590297375119/test-yuva'], 'ua_append' => [0 => 'Symfony/4.1.13', 1 => 'SYMOD/2.0.0']]);
