<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Command/DebugCommand.php';

$this->privates['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(($this->privates['form.registry'] ?? $this->load('getForm_RegistryService.php')), [0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'App\\Form', 2 => 'App\\Form\\User', 3 => 'Symfony\\Bridge\\Doctrine\\Form\\Type', 4 => 'MsgPhp\\User\\Infra\\Form\\Type'], [0 => 'App\\Form\\FileWatcherType', 1 => 'App\\Form\\LookupValuesType', 2 => 'App\\Form\\NexusAnalysisType', 3 => 'App\\Form\\ProjectAssignmentType', 4 => 'App\\Form\\ProjectRateType', 5 => 'App\\Form\\ProjectType', 6 => 'App\\Form\\QueryType', 7 => 'App\\Form\\TaskCategoryType', 8 => 'App\\Form\\TaskQueueType', 9 => 'App\\Form\\TaskTemplateDetailType', 10 => 'App\\Form\\TaskType', 11 => 'App\\Form\\TemplateType', 12 => 'App\\Form\\User\\ForgotPasswordType', 13 => 'App\\Form\\User\\LoginType', 14 => 'App\\Form\\User\\ResetPasswordType', 15 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 16 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 17 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType', 18 => 'MsgPhp\\User\\Infra\\Form\\Type\\HashedPasswordType'], [0 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 1 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 4 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\UploadValidatorExtension', 5 => 'Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension'], [0 => 'Symfony\\Component\\Form\\Extension\\Validator\\ValidatorTypeGuesser', 1 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser']);

$instance->setName('debug:form');

return $instance;
