<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\LoginListener' shared autowired service.

include_once $this->targetDirs[3].'/src/Helper/Utils.php';
include_once $this->targetDirs[3].'/src/EventListener/LoginListener.php';

return $this->privates['App\\EventListener\\LoginListener'] = new \App\EventListener\LoginListener(($this->privates['aws.sqs'] ?? $this->load('getAws_SqsService.php')), ($this->privates['App\\Repository\\AppUserRepository'] ?? $this->load('getAppUserRepositoryService.php')), $this);
