<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.list_checks.command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/liip/monitor-bundle/Command/ListChecksCommand.php';
include_once $this->targetDirs[3].'/vendor/liip/monitor-bundle/Helper/RunnerManager.php';

$this->services['liip_monitor.list_checks.command'] = $instance = new \Liip\MonitorBundle\Command\ListChecksCommand(($this->services['liip_monitor.helper.runner_manager'] ?? ($this->services['liip_monitor.helper.runner_manager'] = new \Liip\MonitorBundle\Helper\RunnerManager($this))), ($this->services['liip_monitor.runner_default'] ?? $this->load('getLiipMonitor_RunnerDefaultService.php')));

$instance->setName('monitor:list');

return $instance;
