<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_monitor.check.php_extensions.default' shared service.

include_once $this->targetDirs[3].'/vendor/zendframework/zenddiagnostics/src/Check/CheckInterface.php';
include_once $this->targetDirs[3].'/vendor/zendframework/zenddiagnostics/src/Check/AbstractCheck.php';
include_once $this->targetDirs[3].'/vendor/zendframework/zenddiagnostics/src/Check/ExtensionLoaded.php';

return $this->services['liip_monitor.check.php_extensions.default'] = new \ZendDiagnostics\Check\ExtensionLoaded($this->parameters['liip_monitor.check.php_extensions.default']);
