<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MsgPhp\Domain\Infra\Console\MessageReceiver' shared service.

include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Console/MessageReceiver.php';

return $this->privates['MsgPhp\\Domain\\Infra\\Console\\MessageReceiver'] = new \MsgPhp\Domain\Infra\Console\MessageReceiver();
