<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MsgPhp\Domain\Infra\Doctrine\MappingCacheWarmer' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/domain/Infra/Doctrine/MappingCacheWarmer.php';

return $this->privates['MsgPhp\\Domain\\Infra\\Doctrine\\MappingCacheWarmer'] = new \MsgPhp\Domain\Infra\Doctrine\MappingCacheWarmer('msgphp/doctrine-mapping', $this->getParameter('msgphp.doctrine.mapping_files'));
