<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'MsgPhp\User\Infra\Security\PasswordHashing' shared autowired service.

include_once $this->targetDirs[3].'/vendor/msgphp/user/Password/PasswordHashingInterface.php';
include_once $this->targetDirs[3].'/vendor/msgphp/user/Infra/Security/PasswordHashing.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Encoder/PasswordEncoderInterface.php';

return $this->privates['MsgPhp\\User\\Infra\\Security\\PasswordHashing'] = new \MsgPhp\User\Infra\Security\PasswordHashing(($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php'))->getEncoder('MsgPhp\\User\\Infra\\Security\\SecurityUser'));
