<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\User\ResetPasswordController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/User/ResetPasswordController.php';

return $this->services['App\\Controller\\User\\ResetPasswordController'] = new \App\Controller\User\ResetPasswordController();
