<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/AccessMap.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcher.php';

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/monitor/health'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/install'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/installsuccess'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/updateconfig'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/setupconfiguration'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/login'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/forgot-password'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/forgot_password'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/reset-password'), [0 => 'IS_AUTHENTICATED_ANONYMOUSLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), [0 => 'ROLE_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/profile'), [0 => 'IS_AUTHENTICATED_FULLY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/accounts'), [0 => 'ROLE_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/users'), [0 => 'ROLE_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/hadoop'), [0 => 'ROLE_HADOOP'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/mpp'), [0 => 'ROLE_DATABASE'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/templates'), [0 => 'ROLE_TEMPLATE'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/watcher'), [0 => 'ROLE_FILE_WATCHER'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/upload'), [0 => 'ROLE_FILE_UPLOAD', 1 => 'ROLE_NEXUS_FILE_UPLOAD'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/simulator'), [0 => 'ROLE_MODEL'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/queries'), [0 => 'ROLE_QUERIES'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/tables'), [0 => 'ROLE_TABLES'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/taskcategory'), [0 => 'ROLE_TASK_CATEGORY'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/taskqueue'), [0 => 'ROLE_TASK_QUEUE'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/task'), [0 => 'ROLE_TASK'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/timesheet'), [0 => 'ROLE_TIMESHEET_SUBMISSION'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/projectrates'), [0 => 'ROLE_PROJECT_RATES'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/projectassignment'), [0 => 'ROLE_TIMESHEET_SUBMISSION', 1 => 'ROLE_TIMESHEET_ASSIGNMENT'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/project'), [0 => 'ROLE_PROJECT'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('/phpinfo'), [0 => 'ROLE_ADMIN'], NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/*'), [0 => 'IS_AUTHENTICATED_FULLY'], NULL);

return $instance;
