/*!40101 SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE = @@TIME_ZONE */;
/*!40103 SET TIME_ZONE = '+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;
/*!40101 SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES = @@SQL_NOTES, SQL_NOTES = 0 */;

--
-- Change the status dates from date to datetime
--
ALTER TABLE `template` ADD COLUMN `table` VARCHAR(255) NOT NULL;

--
-- Add a statusresult field which will be used to record the outcomes of any execution
--
ALTER TABLE `customreport` ADD COLUMN statusresult MEDIUMTEXT DEFAULT NULL;
ALTER TABLE `filewatcher` ADD COLUMN statusresult MEDIUMTEXT DEFAULT NULL;
ALTER TABLE `hadoop_status`
    ADD COLUMN statusresult MEDIUMTEXT DEFAULT NULL,
    ADD COLUMN `color` VARCHAR(25) NOT NULL DEFAULT 'orange';
ALTER TABLE `mpp_status`
    ADD COLUMN statusresult MEDIUMTEXT DEFAULT NULL,
    ADD COLUMN `color` VARCHAR(25) NOT NULL DEFAULT 'orange';
ALTER TABLE `simulation` ADD COLUMN statusresult MEDIUMTEXT DEFAULT NULL;

--
-- Notifications add a read value
--
ALTER TABLE `notification`
    ADD COLUMN `isread` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `color` VARCHAR(25) NOT NULL DEFAULT '#337ab7';
/*!40101 SET SQL_MODE = @OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS = @OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION = @OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES = @OLD_SQL_NOTES */;