/*!40101 SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE = @@TIME_ZONE */;
/*!40103 SET TIME_ZONE = '+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;
/*!40101 SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES = @@SQL_NOTES, SQL_NOTES = 0 */;


-- Table structure for table `fileupload`
--

DROP TABLE IF EXISTS `fileupload`;
CREATE TABLE IF NOT EXISTS `fileupload` (
  `id` bigint(20) AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(100) NOT NULL,
  `folder` varchar(255) DEFAULT NULL,
  `templateid` BIGINT(20) NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `size` int NOT NULL,
  status varchar(255) NOT NULL DEFAULT 'Pending',
  `color` VARCHAR(25) NOT NULL DEFAULT 'orange',
  `statusresult` mediumtext NOT NULL,
  `date` datetime  null,
  `uuid` char(38) NOT NULL,
 `uploadedby` bigint NOT NULL,
  UNIQUE KEY `unique_file_upload_uuid` (`uuid`),
  UNIQUE KEY `unique_file_upload_name_folder` (`name`, `folder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE fileupload
  ADD CONSTRAINT fk_file_upload_template FOREIGN KEY (templateid) REFERENCES template (id);

/*!40101 SET SQL_MODE = @OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS = @OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION = @OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES = @OLD_SQL_NOTES */;