/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Add missing columns to the app user table
--
ALTER TABLE `app_user`
ADD COLUMN `usertype` varchar(255) DEFAULT NULL,
ADD COLUMN `employeecategory` varchar(255) DEFAULT NULL,
ADD COLUMN `onvacation` varchar(255) DEFAULT NULL,
  ADD COLUMN `mobilenumber` varchar(255) DEFAULT NULL,
  ADD COLUMN `homephone` varchar(255) DEFAULT NULL,
ADD COLUMN   `tsgbadgenumber` varchar(255) DEFAULT NULL,
ADD COLUMN   `officeline1` varchar(50) DEFAULT NULL,
ADD COLUMN   `officeline2` varchar(50) DEFAULT NULL,
ADD COLUMN   `faxnumber` varchar(50) DEFAULT NULL,
ADD COLUMN   `address1` varchar(255) DEFAULT NULL,
ADD COLUMN   `address2` varchar(255) DEFAULT NULL,
ADD COLUMN   `stateorprovince` varchar(255) DEFAULT NULL,
ADD COLUMN   `postalcode` varchar(50) DEFAULT NULL,
ADD COLUMN   `country` varchar(255) DEFAULT NULL,
ADD COLUMN   `city` varchar(255) DEFAULT NULL,
ADD COLUMN   `companyname` varchar(255) DEFAULT '',
ADD COLUMN   `companyaddress` varchar(255) DEFAULT '',
ADD COLUMN   `ssn` varchar(20) DEFAULT NULL,
ADD COLUMN   `ein` varchar(20) DEFAULT NULL,
ADD COLUMN   `birthdate` datetime DEFAULT NULL,
ADD COLUMN   `hiredate` datetime DEFAULT NULL,
ADD COLUMN   `employeestartdate` datetime DEFAULT NULL,
ADD COLUMN   `employeeenddate` datetime DEFAULT NULL,
ADD COLUMN   `releasedate` datetime DEFAULT NULL,
ADD COLUMN   `lastreviewdate` datetime DEFAULT NULL,
ADD COLUMN   `nextreviewdate` datetime DEFAULT NULL,
ADD COLUMN   `supervisorname` varchar(255) DEFAULT NULL,
ADD COLUMN   `supervisoremail` varchar(255) DEFAULT NULL,
ADD COLUMN   `supervisorofficeline` varchar(255) DEFAULT NULL,
ADD COLUMN `approver` varchar(255) DEFAULT NULL, 
ADD COLUMN `approveremail` varchar(255) DEFAULT NULL, 
ADD COLUMN `invoiceapprover` varchar(255) DEFAULT NULL, 
ADD COLUMN `invoiceapproveremail` varchar(255) DEFAULT NULL, 
ADD COLUMN `businessmeetingapprover` varchar(255) DEFAULT NULL, 
ADD COLUMN `businessmeetingapproveremail` varchar(255) DEFAULT NULL, 
ADD COLUMN `travelexpenseapprover` varchar(255) DEFAULT NULL, 
ADD COLUMN `travelexpenseapproveremail` varchar(255) DEFAULT NULL, 
ADD COLUMN `odcapprover` varchar(255) DEFAULT NULL, 
ADD COLUMN `odcapproveremail` varchar(255) DEFAULT NULL, 
ADD COLUMN `billsapprover` varchar(255) DEFAULT NULL, 
ADD COLUMN `billsapproveremail` varchar(255) DEFAULT NULL, 
ADD COLUMN   `payrollfrequency` varchar(50) DEFAULT NULL,
ADD COLUMN   `paycode` varchar(10) DEFAULT NULL,
ADD COLUMN   `regularrate` decimal(10,2) NOT NULL DEFAULT '0.00',
ADD COLUMN   `regularratecode` varchar(10) DEFAULT NULL,
ADD COLUMN   `maximumregularhours` decimal(10,1) NOT NULL DEFAULT '8.0',
ADD COLUMN   `overtimeallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `overtimerate` decimal(10,2) DEFAULT NULL,
ADD COLUMN   `overtimeratecode` varchar(10) DEFAULT NULL,
ADD COLUMN   `maximumovertimehoursperday` decimal(10,1) DEFAULT NULL,
ADD COLUMN   `maximumhoursperday` decimal(10,0) NOT NULL DEFAULT '8',
ADD COLUMN   `maximumhoursperweek` decimal(10,0) NOT NULL DEFAULT '40',
ADD COLUMN   `maximumovertimehours` decimal(10,1) DEFAULT NULL DEFAULT '0.0',
ADD COLUMN   `vacationdaysallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `maximumsocialsecurity` decimal(10,0) DEFAULT '0',
ADD COLUMN   `maximumvacationdays` decimal(10,2) DEFAULT '0.00',
ADD COLUMN   `personaldaysallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `maximumpersonaldays` decimal(10,2) DEFAULT '0.00' ,
ADD COLUMN   `paidholidaysallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `maximumpaidholidays` decimal(10,2) DEFAULT '0.00',
ADD COLUMN   `sickdaysallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `maximumsickdays` decimal(10,2) DEFAULT '0.00',
ADD COLUMN   `saturdayworkallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `sundayworkallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `publicholidayworkallowed` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `employeebenefitsbillable` enum('N','Y') NOT NULL DEFAULT 'N',
ADD COLUMN   `invoicecategory` varchar(50) DEFAULT NULL,
ADD COLUMN   `employeejobs` varchar(240) DEFAULT NULL,
ADD COLUMN   `status` varchar(255) DEFAULT NULL,
ADD COLUMN   `createdby` bigint(20) NOT NULL DEFAULT '0',
ADD COLUMN   `datecreated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
ADD COLUMN   `changedpassword` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `lastupdatedby` varchar(20) DEFAULT NULL,
ADD COLUMN   `lastupdatedate` datetime DEFAULT NULL,
ADD COLUMN   `securityquestion` varchar(255) DEFAULT NULL,
ADD COLUMN   `answer` varchar(255) DEFAULT NULL,
ADD COLUMN   `disabledaily` enum('Y','N') NOT NULL DEFAULT 'N',
ADD COLUMN   `passwordexpirydate` datetime DEFAULT NULL,
ADD COLUMN   `canviewemployeeresources` enum('Y','N') DEFAULT 'N',
ADD COLUMN   `canviewpublicholidays` enum('Y','N') DEFAULT 'N',
ADD COLUMN   `canviewpayrolldates` enum('Y','N') DEFAULT 'N',
ADD COLUMN   `canviewtravelpolicy` enum('Y','N') DEFAULT 'N',
ADD COLUMN   `canview401kinformation` enum('Y','N') DEFAULT 'N',
ADD COLUMN   `canviewreferenceinformation` enum('Y','N') DEFAULT 'N',
ADD COLUMN   `ec1_firstname` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_lastname` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_streetaddress` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_city` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_state` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_zipcode` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_homephone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_workphone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_cellphone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec1_relationship` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_firstname` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_lastname` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_streetaddress` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_city` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_state` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_zipcode` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_homephone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_workphone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_cellphone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec2_relationship` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_firstname` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_lastname` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_streetaddress` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_city` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_state` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_zipcode` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_homephone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_workphone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_cellphone` varchar(255) DEFAULT NULL,
ADD COLUMN   `ec3_relationship` varchar(255) DEFAULT NULL,
ADD COLUMN   `permissiontemplate` varchar(255) DEFAULT NULL,
ADD COLUMN   `categoryuser` enum('HRMS','Legal','Healthcare') NOT NULL DEFAULT 'HRMS',
ADD COLUMN   `uniqueid` int(15) DEFAULT NULL,
ADD COLUMN   `week_start` varchar(20) NOT NULL,
ADD COLUMN   `hourly_wage` varchar(8) NOT NULL,
ADD COLUMN   `photo` varchar(250) NOT NULL DEFAULT 'None';

/*!40101 SET SQL_MODE = @OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS = @OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION = @OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES = @OLD_SQL_NOTES */;